"""add_item_metadata_columns

Revision ID: ccda9275bbfa
Revises: a1b2c3d4e5f6
Create Date: 2026-05-01 08:33:56.123103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccda9275bbfa'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('items', sa.Column('primary_color', sa.String(length=20), nullable=True))
    op.add_column('items', sa.Column('secondary_colors', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
    op.add_column('items', sa.Column('style', sa.String(length=30), nullable=True))
    op.add_column('items', sa.Column('material', sa.String(length=30), nullable=True))
    op.add_column('items', sa.Column('width_in', sa.Float(), nullable=True))
    op.add_column('items', sa.Column('height_in', sa.Float(), nullable=True))
    op.add_column('items', sa.Column('depth_in', sa.Float(), nullable=True))
    op.add_column('items', sa.Column('serial_number', sa.String(length=255), nullable=True))
    op.add_column('items', sa.Column('asking_price', sa.Integer(), nullable=True))

    # Backfill: ensure any existing rows have secondary_colors = '[]'.
    # This is redundant under server_default but is safe to keep.
    op.execute("UPDATE items SET secondary_colors = '[]' WHERE secondary_colors IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'asking_price')
    op.drop_column('items', 'serial_number')
    op.drop_column('items', 'depth_in')
    op.drop_column('items', 'height_in')
    op.drop_column('items', 'width_in')
    op.drop_column('items', 'material')
    op.drop_column('items', 'style')
    op.drop_column('items', 'secondary_colors')
    op.drop_column('items', 'primary_color')
    # ### end Alembic commands ###
